 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/places", type: :request do
  # Place. As you add validations to Place, be sure to
  # adjust the attributes here as well.
  let(:user) { FactoryBot.create :user }
  let(:user_shared) { FactoryBot.create :user }

  let(:valid_attributes) {
    {
      "name"=>"private - updated",
      "note"=>"private note",
      "lat"=>"12",
      "lng"=>"12",
      "user_id"=> user.id
    }
  }

  let(:invalid_attributes) {
    {
      "name"=>"private - updated",
      "note"=>"private note",
      "lat"=>"1289192182",
      "lng"=>"12891921821289192182",
      "user_id"=> user.id
    }
  }

  before do
    ENV['GOOGLE_MAPS_API_KEY'] = 'test-key'
    login_as_user
  end

  describe "GET /index" do
    context "all places" do
      it "renders a successful response" do
        Place.create! valid_attributes
        get places_url
        expect(response).to be_successful
      end
    end

    context "places shared with me" do
      it "renders a successful response" do
        Place.create! valid_attributes
        get places_url params: {selection: 'places_shared_with_me'}
        expect(response).to be_successful
      end
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      place = Place.create! valid_attributes
      get place_url(place)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_place_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      place = Place.create! valid_attributes
      get edit_place_url(place)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Place" do
        expect {
          post places_url, params: { place: valid_attributes.merge({"shared_users"=>[user_shared.email]}) }
        }.to change(Place, :count).by(1)
        .and change(Share, :count).by(1)
      end

      it "redirects to the created place" do
        post places_url, params: { place: valid_attributes }
        expect(response).to redirect_to(place_url(Place.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Place" do
        expect {
          post places_url, params: { place: invalid_attributes }
        }.to change(Place, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post places_url, params: { place: invalid_attributes }
        expect(response.status).to eq(422)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          "name"=>"updated name",
          "note"=>"private note",
          "lat"=>"12",
          "lng"=>"12",
          "user_id"=> user.id
        }
      }

      it "updates the requested place" do
        place = Place.create! valid_attributes
        patch place_url(place), params: { place: new_attributes }
        place.reload
        expect(place.name).to eq new_attributes['name']
      end

      it "redirects to the place" do
        place = Place.create! valid_attributes
        patch place_url(place), params: { place: new_attributes }
        place.reload
        expect(response).to redirect_to(place_url(place))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        place = Place.create! valid_attributes
        patch place_url(place), params: { place: invalid_attributes }
        expect(response.status).to eq(422)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested place" do
      place = Place.create! valid_attributes
      expect {
        delete place_url(place)
      }.to change(Place, :count).by(-1)
    end

    it "redirects to the places list" do
      place = Place.create! valid_attributes
      delete place_url(place)
      expect(response).to redirect_to(places_url)
    end
  end
end
